### ISSUE TITLE
Copy-CSShadowCopyItem

### ISSUE THREAD

**Issue by secabstraction** [PowerShellMafia/CimSweep#20]
This doesn't work running as admin on win10, localhost, for me. Trying to grab the AmCache for some other testing. Also, what's the point of [this error](https://github.com/PowerShellMafia/CimSweep/blob/dev/CimSweep/Offense/ShadowCopy.ps1#L157)?

If I step through the code in ISE, it does work... wtf smalls? (Maybe there's a race condition where the shadowcopy is getting deleted before the file is copied.)

**Comment by mattifestation** [comment]
Hey smalls. :P

Sorry. I'm going to close this. The decision was made to not include and functions in CIMSweep that alter system state.
